In [4]:
import numpy as np

In [5]:
v1 = np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [7]:
v1 = np.arange(5)
print(v1)

v2 = np.arange(1,10,2, dtype=int)
print(v2)

v3 = np.arange(3.5,10.5,2, dtype=float)
print(v3)

v4 = np.arange(1,10,2)**2
print(v4)

v5 = np.arange(1,10,2)**3
print(v5)

[0 1 2 3 4]
[1 3 5 7 9]
[3.5 5.5 7.5 9.5]
[ 1  9 25 49 81]
[  1  27 125 343 729]


In [9]:
# 행렬
v1 = np.arange(12)
print(v1)
v2 = v1.reshape(2,6)
print(v2)
v3 = v1.reshape(2,6, order='F')
print(v3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [11]:
# 행렬 계산
v1 = np.arange(1,5).reshape(2,2)
print(np.add(v1,v1))
print(np.subtract(v1,v1))
print(np.multiply(v1,v1))
print(np.dot(v1,v1))

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [12]:
# 다차원 배열
v1 = np.arange(12)
print(v1)
v2=v1.reshape(2,3,2,order='F')
print(v2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [13]:
v3 = np.arange(3.5,10.5,2,dtype=float)
print(v3)
v4 = np.arange(1,5).reshape(2,2)
print(v4)
print(np.amax(v3))
print(np.amax(v4))
print(v3.dtype)
print(v4.dtype)

[3.5 5.5 7.5 9.5]
[[1 2]
 [3 4]]
9.5
4
float64
int64


In [14]:
import pandas as pd
from pandas import Series,DataFrame

In [15]:
a = Series([1,3,5,7])
print(a)
print(a.values)
print(a.index)

a2 = pd.Series([1,3,5,7],index=['a','b','c','d'])
print(a2)

0    1
1    3
2    5
3    7
dtype: int64
[1 3 5 7]
RangeIndex(start=0, stop=4, step=1)
a    1
b    3
c    5
d    7
dtype: int64


In [16]:
df = pd.read_csv('/Users/kwonsuhyun/python/bigdata/data/EX_GrapeData.csv')
df

continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]

In [17]:
df_columns = df.copy()
df_columns.columns

Index(['continent', 'brand', 'size', 'period', 'price'], dtype='object')

In [21]:
df_columns = df_columns[['size', 'period', 'price']]
df_columns.head()

size  period price
0  10.7   47.65   144
1  14.0   63.13   215
2   9.0   58.76   105
3   8.0   34.88    69
4  10.0   55.53   134

In [22]:
df_columns.rename(columns={'period':'time'},inplace=True)
df_columns.columns

/Users/kwonsuhyun/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4223: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(**kwargs)


Index(['size', 'time', 'price'], dtype='object')

In [23]:
df_columns['growth'] = df_columns['size']/df_columns['time']
df_columns.head()

/Users/kwonsuhyun/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


size   time price    growth
0  10.7  47.65   144  0.224554
1  14.0  63.13   215  0.221765
2   9.0  58.76   105  0.153165
3   8.0  34.88    69  0.229358
4  10.0  55.53   134  0.180083

In [24]:
del df_columns['growth']

In [25]:
df_columns

size   time price
0   10.7  47.65   144
1   14.0  63.13   215
2    9.0  58.76   105
3    8.0  34.88    69
4   10.0  55.53   134
..   ...    ...   ...
58   5.0  16.66  21.5
59  21.0  43.00      
60   5.0  12.00      
61  13.0  20.00      
62  31.0  19.00      

[63 rows x 3 columns]

In [26]:
df_continent_brand=df[(df['continent']==1)&(df['brand']==1)]
df_continent_brand.head()

continent  brand  size  period price
3           1      1   8.0   34.88    69
11          1      1  10.4   17.67    54
12          1      1   7.4   16.41    39
13          1      1   5.4   12.02  29.5
16          1      1   6.0   23.21    42

In [31]:
df['brand'].value_counts()

2    24
1    23
3    16
Name: brand, dtype: int64

In [33]:
def brand_groups(series):
    if series==1:
        return 1
    elif series==2:
        return 1
    elif series==3:
        return 2

df['re_brand']=df['brand'].apply(brand_groups)
df.head()

continent  brand  size  period price  re_brand
0          2      2  10.7   47.65   144         1
1          2      3  14.0   63.13   215         2
2          2      2   9.0   58.76   105         1
3          1      1   8.0   34.88    69         1
4          2      2  10.0   55.53   134         1

In [34]:
df = pd.read_csv('/Users/kwonsuhyun/python/bigdata/data/EX_GrapeData.csv')
df.head()

continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134

In [35]:
df_num = df.to_numpy()
df_num

array([[2, 2, 10.7, 47.65, '144'],
       [2, 3, 14.0, 63.13, '215'],
       [2, 2, 9.0, 58.76, '105'],
       [1, 1, 8.0, 34.88, '69'],
       [2, 2, 10.0, 55.53, '134'],
       [2, 2, 10.5, 43.14, '129'],
       [2, 2, 16.0, 54.86, '155'],
       [2, 1, 15.0, 44.14, '99'],
       [2, 1, 6.5, 17.46, '38.5'],
       [2, 1, 5.0, 21.04, '36.5'],
       [2, 2, 25.0, 109.38, '260'],
       [1, 1, 10.4, 17.67, '54'],
       [1, 1, 7.4, 16.41, '39'],
       [1, 1, 5.4, 12.02, '29.5'],
       [2, 2, 15.4, 49.48, '109'],
       [2, 1, 12.4, 48.74, '89.5'],
       [1, 1, 6.0, 23.21, '42'],
       [1, 1, 9.0, 28.64, '65'],
       [1, 3, 9.0, 44.95, '115'],
       [1, 1, 12.4, 23.77, '49.5'],
       [1, 1, 7.5, 20.21, '36.5'],
       [1, 3, 14.0, 32.62, '109'],
       [1, 1, 7.0, 17.84, '45'],
       [1, 2, 9.0, 22.82, '58'],
       [1, 2, 12.0, 29.48, '89'],
       [1, 1, 5.5, 15.61, '30'],
       [1, 2, 6.0, 13.25, '31'],
       [1, 3, 12.0, 45.78, '119'],
       [2, 1, 5.5, 26.53, '22'],
     

In [36]:
df_pd = pd.DataFrame(df_num)
df_pd.head()

0  1     2      3    4
0  2  2  10.7  47.65  144
1  2  3    14  63.13  215
2  2  2     9  58.76  105
3  1  1     8  34.88   69
4  2  2    10  55.53  134

In [38]:
df_pd2 = pd.DataFrame(data=df_num,columns=['con','brand','size','period','price'])
df_pd2.head()

con brand  size period price
0   2     2  10.7  47.65   144
1   2     3    14  63.13   215
2   2     2     9  58.76   105
3   1     1     8  34.88    69
4   2     2    10  55.53   134